name: Run Gradle on PRs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gradle:
    #strategy:
    #  matrix:
    #    os: [ubuntu-latest, macos-latest, windows-latest]
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build

    - name: Upload build files to AWS instance
      run: echo TODO upload
      
    - name: Build & Deploy
      run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_PRIVATE_KEY }}@${{secrets.EC2_DNS_ADDRESS}} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ubuntu/ &&
              ls -la
              '
